version: '3.5'

services:
  todolist-web:
    container_name: todolist-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8000:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - todolist-network
    depends_on:
      - todolist-backend

  todolist-backend:
    container_name: todolist-backend
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - todolist-network
    depends_on:
      - todolist-db

  todolist-db:
    container_name: todolist-db
    image: mysql:8.0
    ports:
      - 40000:3306
    env_file:
      - ${PWD}/docker.env
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - todolist-database-data:/var/lib/mysql
    networks:
      - todolist-network

###> doctrine/doctrine-bundle ###
    #  database:
    #image: postgres:${POSTGRES_VERSION:-13}-alpine
      #environment:
      #POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      #POSTGRES_USER: ${POSTGRES_USER:-symfony}
      #volumes:
      #- db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  #db-data:
###< doctrine/doctrine-bundle ###
  todolist-database-data:

networks:
  todolist-network:
    external: true
